export interface RegionChildSeed {
  code: string;
  name: string;
  sortOrder: number;
}

export interface RegionGroupSeed {
  code: string;
  name: string;
  sortOrder: number;
  children?: RegionChildSeed[];
}

export const REGION_GROUPS: RegionGroupSeed[] = [
  {
    code: 'KR-00',
    name: '전국',
    sortOrder: 0,
  },
  {
    code: 'KR-01',
    name: '서울',
    sortOrder: 1,
    children: [
      { code: 'KR-01-00', name: '서울 전체', sortOrder: 0 },
      { code: 'KR-01-01', name: '강남구', sortOrder: 1 },
      { code: 'KR-01-02', name: '강동구', sortOrder: 2 },
      { code: 'KR-01-03', name: '강북구', sortOrder: 3 },
      { code: 'KR-01-04', name: '강서구', sortOrder: 4 },
      { code: 'KR-01-05', name: '관악구', sortOrder: 5 },
      { code: 'KR-01-06', name: '광진구', sortOrder: 6 },
      { code: 'KR-01-07', name: '구로구', sortOrder: 7 },
      { code: 'KR-01-08', name: '금천구', sortOrder: 8 },
      { code: 'KR-01-09', name: '노원구', sortOrder: 9 },
      { code: 'KR-01-10', name: '도봉구', sortOrder: 10 },
      { code: 'KR-01-11', name: '동대문구', sortOrder: 11 },
      { code: 'KR-01-12', name: '동작구', sortOrder: 12 },
      { code: 'KR-01-13', name: '마포구', sortOrder: 13 },
      { code: 'KR-01-14', name: '서대문구', sortOrder: 14 },
      { code: 'KR-01-15', name: '서초구', sortOrder: 15 },
      { code: 'KR-01-16', name: '성동구', sortOrder: 16 },
      { code: 'KR-01-17', name: '성북구', sortOrder: 17 },
      { code: 'KR-01-18', name: '송파구', sortOrder: 18 },
      { code: 'KR-01-19', name: '양천구', sortOrder: 19 },
      { code: 'KR-01-20', name: '영등포구', sortOrder: 20 },
      { code: 'KR-01-21', name: '용산구', sortOrder: 21 },
      { code: 'KR-01-22', name: '은평구', sortOrder: 22 },
      { code: 'KR-01-23', name: '종로구', sortOrder: 23 },
      { code: 'KR-01-24', name: '중구', sortOrder: 24 },
      { code: 'KR-01-25', name: '중랑구', sortOrder: 25 },
    ],
  },
  {
    code: 'KR-02',
    name: '세종',
    sortOrder: 2,
    children: [
      { code: 'KR-02-00', name: '세종 전체', sortOrder: 0 },
      { code: 'KR-02-01', name: '세종', sortOrder: 1 },
    ],
  },
  {
    code: 'KR-03',
    name: '강원',
    sortOrder: 3,
    children: [
      { code: 'KR-03-00', name: '강원 전체', sortOrder: 0 },
      { code: 'KR-03-01', name: '강릉시', sortOrder: 1 },
      { code: 'KR-03-02', name: '고성군', sortOrder: 2 },
      { code: 'KR-03-03', name: '동해시', sortOrder: 3 },
      { code: 'KR-03-04', name: '삼척시', sortOrder: 4 },
      { code: 'KR-03-05', name: '속초시', sortOrder: 5 },
      { code: 'KR-03-06', name: '양구군', sortOrder: 6 },
      { code: 'KR-03-07', name: '양양군', sortOrder: 7 },
      { code: 'KR-03-08', name: '영월군', sortOrder: 8 },
      { code: 'KR-03-09', name: '원주시', sortOrder: 9 },
      { code: 'KR-03-10', name: '인제군', sortOrder: 10 },
      { code: 'KR-03-11', name: '정선군', sortOrder: 11 },
      { code: 'KR-03-12', name: '철원군', sortOrder: 12 },
      { code: 'KR-03-13', name: '춘천시', sortOrder: 13 },
      { code: 'KR-03-14', name: '태백시', sortOrder: 14 },
      { code: 'KR-03-15', name: '평창군', sortOrder: 15 },
      { code: 'KR-03-16', name: '홍천군', sortOrder: 16 },
      { code: 'KR-03-17', name: '화천군', sortOrder: 17 },
      { code: 'KR-03-18', name: '횡성군', sortOrder: 18 },
    ],
  },
  {
    code: 'KR-04',
    name: '인천',
    sortOrder: 4,
    children: [
      { code: 'KR-04-00', name: '인천 전체', sortOrder: 0 },
      { code: 'KR-04-01', name: '강화군', sortOrder: 1 },
      { code: 'KR-04-02', name: '계양구', sortOrder: 2 },
      { code: 'KR-04-03', name: '남동구', sortOrder: 3 },
      { code: 'KR-04-04', name: '동구', sortOrder: 4 },
      { code: 'KR-04-05', name: '미추홀구', sortOrder: 5 },
      { code: 'KR-04-06', name: '부평구', sortOrder: 6 },
      { code: 'KR-04-07', name: '서구', sortOrder: 7 },
      { code: 'KR-04-08', name: '연수구', sortOrder: 8 },
      { code: 'KR-04-09', name: '옹진군', sortOrder: 9 },
      { code: 'KR-04-10', name: '중구', sortOrder: 10 },
    ],
  },
  {
    code: 'KR-05',
    name: '경기',
    sortOrder: 5,
    children: [
      { code: 'KR-05-00', name: '경기 전체', sortOrder: 0 },
      { code: 'KR-05-01', name: '가평군', sortOrder: 1 },
      { code: 'KR-05-02', name: '고양시 덕양구', sortOrder: 2 },
      { code: 'KR-05-03', name: '고양시 일산동구', sortOrder: 3 },
      { code: 'KR-05-04', name: '고양시 일산서구', sortOrder: 4 },
      { code: 'KR-05-05', name: '과천시', sortOrder: 5 },
      { code: 'KR-05-06', name: '광명시', sortOrder: 6 },
      { code: 'KR-05-07', name: '광주시', sortOrder: 7 },
      { code: 'KR-05-08', name: '구리시', sortOrder: 8 },
      { code: 'KR-05-09', name: '군포시', sortOrder: 9 },
      { code: 'KR-05-10', name: '김포시', sortOrder: 10 },
      { code: 'KR-05-11', name: '남양주시', sortOrder: 11 },
      { code: 'KR-05-12', name: '동두천시', sortOrder: 12 },
      { code: 'KR-05-13', name: '부천시 소사구', sortOrder: 13 },
      { code: 'KR-05-14', name: '부천시 오정구', sortOrder: 14 },
      { code: 'KR-05-15', name: '부천시 원미구', sortOrder: 15 },
      { code: 'KR-05-16', name: '성남시 분당구', sortOrder: 16 },
      { code: 'KR-05-17', name: '성남시 수정구', sortOrder: 17 },
      { code: 'KR-05-18', name: '성남시 중원구', sortOrder: 18 },
      { code: 'KR-05-19', name: '수원시 권선구', sortOrder: 19 },
      { code: 'KR-05-20', name: '수원시 영통구', sortOrder: 20 },
      { code: 'KR-05-21', name: '수원시 장안구', sortOrder: 21 },
      { code: 'KR-05-22', name: '수원시 팔달구', sortOrder: 22 },
      { code: 'KR-05-23', name: '시흥시', sortOrder: 23 },
      { code: 'KR-05-24', name: '안산시 단원구', sortOrder: 24 },
      { code: 'KR-05-25', name: '안산시 상록구', sortOrder: 25 },
      { code: 'KR-05-26', name: '안성시', sortOrder: 26 },
      { code: 'KR-05-27', name: '안양시 동안구', sortOrder: 27 },
      { code: 'KR-05-28', name: '안양시 만안구', sortOrder: 28 },
      { code: 'KR-05-29', name: '양주시', sortOrder: 29 },
      { code: 'KR-05-30', name: '양평군', sortOrder: 30 },
      { code: 'KR-05-31', name: '여주시', sortOrder: 31 },
      { code: 'KR-05-32', name: '연천군', sortOrder: 32 },
      { code: 'KR-05-33', name: '오산시', sortOrder: 33 },
      { code: 'KR-05-34', name: '용인시 기흥구', sortOrder: 34 },
      { code: 'KR-05-35', name: '용인시 수지구', sortOrder: 35 },
      { code: 'KR-05-36', name: '용인시 처인구', sortOrder: 36 },
      { code: 'KR-05-37', name: '의왕시', sortOrder: 37 },
      { code: 'KR-05-38', name: '의정부시', sortOrder: 38 },
      { code: 'KR-05-39', name: '이천시', sortOrder: 39 },
      { code: 'KR-05-40', name: '파주시', sortOrder: 40 },
      { code: 'KR-05-41', name: '평택시', sortOrder: 41 },
      { code: 'KR-05-42', name: '포천시', sortOrder: 42 },
      { code: 'KR-05-43', name: '하남시', sortOrder: 43 },
      { code: 'KR-05-44', name: '화성시', sortOrder: 44 },
    ],
  },
  {
    code: 'KR-06',
    name: '충북',
    sortOrder: 6,
    children: [
      { code: 'KR-06-00', name: '충북 전체', sortOrder: 0 },
      { code: 'KR-06-01', name: '괴산군', sortOrder: 1 },
      { code: 'KR-06-02', name: '단양군', sortOrder: 2 },
      { code: 'KR-06-03', name: '보은군', sortOrder: 3 },
      { code: 'KR-06-04', name: '영동군', sortOrder: 4 },
      { code: 'KR-06-05', name: '옥천군', sortOrder: 5 },
      { code: 'KR-06-06', name: '음성군', sortOrder: 6 },
      { code: 'KR-06-07', name: '제천시', sortOrder: 7 },
      { code: 'KR-06-08', name: '증평군', sortOrder: 8 },
      { code: 'KR-06-09', name: '진천군', sortOrder: 9 },
      { code: 'KR-06-10', name: '청주시 상당구', sortOrder: 10 },
      { code: 'KR-06-11', name: '청주시 서원구', sortOrder: 11 },
      { code: 'KR-06-12', name: '청주시 청원구', sortOrder: 12 },
      { code: 'KR-06-13', name: '청주시 흥덕구', sortOrder: 13 },
      { code: 'KR-06-14', name: '충주시', sortOrder: 14 },
    ],
  },
  {
    code: 'KR-07',
    name: '충남',
    sortOrder: 7,
    children: [
      { code: 'KR-07-00', name: '충남 전체', sortOrder: 0 },
      { code: 'KR-07-01', name: '계룡시', sortOrder: 1 },
      { code: 'KR-07-02', name: '공주시', sortOrder: 2 },
      { code: 'KR-07-03', name: '금산군', sortOrder: 3 },
      { code: 'KR-07-04', name: '논산시', sortOrder: 4 },
      { code: 'KR-07-05', name: '당진시', sortOrder: 5 },
      { code: 'KR-07-06', name: '보령시', sortOrder: 6 },
      { code: 'KR-07-07', name: '부여군', sortOrder: 7 },
      { code: 'KR-07-08', name: '서산시', sortOrder: 8 },
      { code: 'KR-07-09', name: '서천군', sortOrder: 9 },
      { code: 'KR-07-10', name: '아산시', sortOrder: 10 },
      { code: 'KR-07-11', name: '예산군', sortOrder: 11 },
      { code: 'KR-07-12', name: '천안시 동남구', sortOrder: 12 },
      { code: 'KR-07-13', name: '천안시 서북구', sortOrder: 13 },
      { code: 'KR-07-14', name: '청양군', sortOrder: 14 },
      { code: 'KR-07-15', name: '태안군', sortOrder: 15 },
      { code: 'KR-07-16', name: '홍성군', sortOrder: 16 },
    ],
  },
  {
    code: 'KR-08',
    name: '경북',
    sortOrder: 8,
    children: [
      { code: 'KR-08-00', name: '경북 전체', sortOrder: 0 },
      { code: 'KR-08-01', name: '경산시', sortOrder: 1 },
      { code: 'KR-08-02', name: '경주시', sortOrder: 2 },
      { code: 'KR-08-03', name: '고령군', sortOrder: 3 },
      { code: 'KR-08-04', name: '구미시', sortOrder: 4 },
      { code: 'KR-08-05', name: '김천시', sortOrder: 5 },
      { code: 'KR-08-06', name: '문경시', sortOrder: 6 },
      { code: 'KR-08-07', name: '봉화군', sortOrder: 7 },
      { code: 'KR-08-08', name: '상주시', sortOrder: 8 },
      { code: 'KR-08-09', name: '성주군', sortOrder: 9 },
      { code: 'KR-08-10', name: '안동시', sortOrder: 10 },
      { code: 'KR-08-11', name: '영덕군', sortOrder: 11 },
      { code: 'KR-08-12', name: '영양군', sortOrder: 12 },
      { code: 'KR-08-13', name: '영주시', sortOrder: 13 },
      { code: 'KR-08-14', name: '영천시', sortOrder: 14 },
      { code: 'KR-08-15', name: '예천군', sortOrder: 15 },
      { code: 'KR-08-16', name: '울릉군', sortOrder: 16 },
      { code: 'KR-08-17', name: '울진군', sortOrder: 17 },
      { code: 'KR-08-18', name: '의성군', sortOrder: 18 },
      { code: 'KR-08-19', name: '청도군', sortOrder: 19 },
      { code: 'KR-08-20', name: '청송군', sortOrder: 20 },
      { code: 'KR-08-21', name: '칠곡군', sortOrder: 21 },
      { code: 'KR-08-22', name: '포항시 남구', sortOrder: 22 },
      { code: 'KR-08-23', name: '포항시 북구', sortOrder: 23 },
    ],
  },
  {
    code: 'KR-09',
    name: '대전',
    sortOrder: 9,
    children: [
      { code: 'KR-09-00', name: '대전 전체', sortOrder: 0 },
      { code: 'KR-09-01', name: '대덕구', sortOrder: 1 },
      { code: 'KR-09-02', name: '동구', sortOrder: 2 },
      { code: 'KR-09-03', name: '서구', sortOrder: 3 },
      { code: 'KR-09-04', name: '유성구', sortOrder: 4 },
      { code: 'KR-09-05', name: '중구', sortOrder: 5 },
    ],
  },
  {
    code: 'KR-10',
    name: '대구',
    sortOrder: 10,
    children: [
      { code: 'KR-10-00', name: '대구 전체', sortOrder: 0 },
      { code: 'KR-10-01', name: '군위군', sortOrder: 1 },
      { code: 'KR-10-02', name: '남구', sortOrder: 2 },
      { code: 'KR-10-03', name: '달서구', sortOrder: 3 },
      { code: 'KR-10-04', name: '달성군', sortOrder: 4 },
      { code: 'KR-10-05', name: '동구', sortOrder: 5 },
      { code: 'KR-10-06', name: '북구', sortOrder: 6 },
      { code: 'KR-10-07', name: '서구', sortOrder: 7 },
      { code: 'KR-10-08', name: '수성구', sortOrder: 8 },
      { code: 'KR-10-09', name: '중구', sortOrder: 9 },
    ],
  },
  {
    code: 'KR-11',
    name: '전북',
    sortOrder: 11,
    children: [
      { code: 'KR-11-00', name: '전북 전체', sortOrder: 0 },
      { code: 'KR-11-01', name: '고창군', sortOrder: 1 },
      { code: 'KR-11-02', name: '군산시', sortOrder: 2 },
      { code: 'KR-11-03', name: '김제시', sortOrder: 3 },
      { code: 'KR-11-04', name: '남원시', sortOrder: 4 },
      { code: 'KR-11-05', name: '무주군', sortOrder: 5 },
      { code: 'KR-11-06', name: '부안군', sortOrder: 6 },
      { code: 'KR-11-07', name: '순창군', sortOrder: 7 },
      { code: 'KR-11-08', name: '완주군', sortOrder: 8 },
      { code: 'KR-11-09', name: '익산시', sortOrder: 9 },
      { code: 'KR-11-10', name: '임실군', sortOrder: 10 },
      { code: 'KR-11-11', name: '장수군', sortOrder: 11 },
      { code: 'KR-11-12', name: '전주시 덕진구', sortOrder: 12 },
      { code: 'KR-11-13', name: '전주시 완산구', sortOrder: 13 },
      { code: 'KR-11-14', name: '정읍시', sortOrder: 14 },
      { code: 'KR-11-15', name: '진안군', sortOrder: 15 },
    ],
  },
  {
    code: 'KR-12',
    name: '경남',
    sortOrder: 12,
    children: [
      { code: 'KR-12-00', name: '경남 전체', sortOrder: 0 },
      { code: 'KR-12-01', name: '거제시', sortOrder: 1 },
      { code: 'KR-12-02', name: '거창군', sortOrder: 2 },
      { code: 'KR-12-03', name: '고성군', sortOrder: 3 },
      { code: 'KR-12-04', name: '김해시', sortOrder: 4 },
      { code: 'KR-12-05', name: '남해군', sortOrder: 5 },
      { code: 'KR-12-06', name: '밀양시', sortOrder: 6 },
      { code: 'KR-12-07', name: '사천시', sortOrder: 7 },
      { code: 'KR-12-08', name: '산청군', sortOrder: 8 },
      { code: 'KR-12-09', name: '양산시', sortOrder: 9 },
      { code: 'KR-12-10', name: '의령군', sortOrder: 10 },
      { code: 'KR-12-11', name: '진주시', sortOrder: 11 },
      { code: 'KR-12-12', name: '창녕군', sortOrder: 12 },
      { code: 'KR-12-13', name: '창원시 마산합포구', sortOrder: 13 },
      { code: 'KR-12-14', name: '창원시 마산회원구', sortOrder: 14 },
      { code: 'KR-12-15', name: '창원시 성산구', sortOrder: 15 },
      { code: 'KR-12-16', name: '창원시 의창구', sortOrder: 16 },
      { code: 'KR-12-17', name: '창원시 진해구', sortOrder: 17 },
      { code: 'KR-12-18', name: '통영시', sortOrder: 18 },
      { code: 'KR-12-19', name: '하동군', sortOrder: 19 },
      { code: 'KR-12-20', name: '함안군', sortOrder: 20 },
      { code: 'KR-12-21', name: '함양군', sortOrder: 21 },
      { code: 'KR-12-22', name: '합천군', sortOrder: 22 },
    ],
  },
  {
    code: 'KR-13',
    name: '울산',
    sortOrder: 13,
    children: [
      { code: 'KR-13-00', name: '울산 전체', sortOrder: 0 },
      { code: 'KR-13-01', name: '남구', sortOrder: 1 },
      { code: 'KR-13-02', name: '동구', sortOrder: 2 },
      { code: 'KR-13-03', name: '북구', sortOrder: 3 },
      { code: 'KR-13-04', name: '울주군', sortOrder: 4 },
      { code: 'KR-13-05', name: '중구', sortOrder: 5 },
    ],
  },
  {
    code: 'KR-14',
    name: '광주',
    sortOrder: 14,
    children: [
      { code: 'KR-14-00', name: '광주 전체', sortOrder: 0 },
      { code: 'KR-14-01', name: '광산구', sortOrder: 1 },
      { code: 'KR-14-02', name: '남구', sortOrder: 2 },
      { code: 'KR-14-03', name: '동구', sortOrder: 3 },
      { code: 'KR-14-04', name: '북구', sortOrder: 4 },
      { code: 'KR-14-05', name: '서구', sortOrder: 5 },
    ],
  },
  {
    code: 'KR-15',
    name: '부산',
    sortOrder: 15,
    children: [
      { code: 'KR-15-00', name: '부산 전체', sortOrder: 0 },
      { code: 'KR-15-01', name: '강서구', sortOrder: 1 },
      { code: 'KR-15-02', name: '금정구', sortOrder: 2 },
      { code: 'KR-15-03', name: '기장군', sortOrder: 3 },
      { code: 'KR-15-04', name: '남구', sortOrder: 4 },
      { code: 'KR-15-05', name: '동구', sortOrder: 5 },
      { code: 'KR-15-06', name: '동래구', sortOrder: 6 },
      { code: 'KR-15-07', name: '부산진구', sortOrder: 7 },
      { code: 'KR-15-08', name: '북구', sortOrder: 8 },
      { code: 'KR-15-09', name: '사상구', sortOrder: 9 },
      { code: 'KR-15-10', name: '사하구', sortOrder: 10 },
      { code: 'KR-15-11', name: '서구', sortOrder: 11 },
      { code: 'KR-15-12', name: '수영구', sortOrder: 12 },
      { code: 'KR-15-13', name: '연제구', sortOrder: 13 },
      { code: 'KR-15-14', name: '영도구', sortOrder: 14 },
      { code: 'KR-15-15', name: '중구', sortOrder: 15 },
      { code: 'KR-15-16', name: '해운대구', sortOrder: 16 },
    ],
  },
  {
    code: 'KR-16',
    name: '전남',
    sortOrder: 16,
    children: [
      { code: 'KR-16-00', name: '전남 전체', sortOrder: 0 },
      { code: 'KR-16-01', name: '강진군', sortOrder: 1 },
      { code: 'KR-16-02', name: '고흥군', sortOrder: 2 },
      { code: 'KR-16-03', name: '곡성군', sortOrder: 3 },
      { code: 'KR-16-04', name: '광양시', sortOrder: 4 },
      { code: 'KR-16-05', name: '구례군', sortOrder: 5 },
      { code: 'KR-16-06', name: '나주시', sortOrder: 6 },
      { code: 'KR-16-07', name: '담양군', sortOrder: 7 },
      { code: 'KR-16-08', name: '목포시', sortOrder: 8 },
      { code: 'KR-16-09', name: '무안군', sortOrder: 9 },
      { code: 'KR-16-10', name: '보성군', sortOrder: 10 },
      { code: 'KR-16-11', name: '순천시', sortOrder: 11 },
      { code: 'KR-16-12', name: '신안군', sortOrder: 12 },
      { code: 'KR-16-13', name: '여수시', sortOrder: 13 },
      { code: 'KR-16-14', name: '영광군', sortOrder: 14 },
      { code: 'KR-16-15', name: '영암군', sortOrder: 15 },
      { code: 'KR-16-16', name: '완도군', sortOrder: 16 },
      { code: 'KR-16-17', name: '장성군', sortOrder: 17 },
      { code: 'KR-16-18', name: '장흥군', sortOrder: 18 },
      { code: 'KR-16-19', name: '진도군', sortOrder: 19 },
      { code: 'KR-16-20', name: '함평군', sortOrder: 20 },
      { code: 'KR-16-21', name: '해남군', sortOrder: 21 },
      { code: 'KR-16-22', name: '화순군', sortOrder: 22 },
    ],
  },
  {
    code: 'KR-17',
    name: '제주',
    sortOrder: 17,
    children: [
      { code: 'KR-17-00', name: '제주 전체', sortOrder: 0 },
      { code: 'KR-17-01', name: '서귀포시', sortOrder: 1 },
      { code: 'KR-17-02', name: '제주시', sortOrder: 2 },
    ],
  },
];

export interface FlatRegionSeed {
  code: string;
  name: string;
  depth: number;
  parentCode: string | null;
  sortOrder: number;
}

export const REGION_SEED: FlatRegionSeed[] = REGION_GROUPS.flatMap((group) => {
  const parent: FlatRegionSeed = {
    code: group.code,
    name: group.name,
    depth: 1,
    parentCode: null,
    sortOrder: group.sortOrder,
  };

  const children =
    group.children?.map((child) => ({
      code: child.code,
      name: child.name,
      depth: 2,
      parentCode: group.code,
      sortOrder: child.sortOrder,
    })) ?? [];

  return [parent, ...children];
});
